include:
  - board: seeeduino_xiao_ble
    shield: ehrbl_left
    snippet: studio-rpc-usb-uart
    artifact-name: ehrbl_caster_left_direct
  - board: seeeduino_xiao_ble
    shield: ehrbl_right
    artifact-name: ehrbl_caster_right_direct

  - board: seeeduino_xiao_ble
    shield: ehrbl_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DDTS_EXTRA_CPPFLAGS="-DDIRECT"
    artifact-name: ehrbl_caster_left_direct
  - board: seeeduino_xiao_ble
    shield: ehrbl_right
    cmake-args: -DDTS_EXTRA_CPPFLAGS="-DDIRECT"
    artifact-name: ehrbl_caster_right_direct

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset
